# yaml-language-server: $schema=https://json.schemastore.org/dependabot-2.0.json
version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    versioning-strategy: "increase"
    groups:
      npm-production-dependencies:
        dependency-type: "production"
        update-types: ["minor", "patch"]
      npm-development-dependencies:
        dependency-type: "development"
        update-types: ["minor", "patch"]

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "node"
        versions: ["> 22.x"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
